name: Deploy Stages Wise

on:
  workflow_dispatch:     

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./Environment/Dev

      - name: Terraform validate
        run: terraform validate
        working-directory: ./Environment/Dev

  plan:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./Environment/Dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Environment/Dev

